# Generated by Django 6.0.2 on 2026-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tyoe',
            new_name='post_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='easy', max_length=10),
            preserve_default=False,
        ),
    ]
