# Generated by Django 6.0.2 on 2026-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_tyoe_post_post_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price',
            field=models.CharField(default='Price per Person', max_length=100),
            preserve_default=False,
        ),
    ]
